accessing
exception: anException

	error := anException.